version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=28848
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
