version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Expose port for Cloudflare Tunnel or reverse proxy
    ports:
      - "28848:28848"
    environment:
      - NODE_ENV=production
      - PORT=28848
      - HOSTNAME=0.0.0.0
    env_file:
      - .env.local
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:28848/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
